name: "pr-comment"
description: "Adds PR changes as comment"
inputs:
  owner:
    description: "The owner of the repo (user or org)"
    required: true
  repo:
    description: "The repo name"
    required: true
  pr_number:
    description: "The number of the pull request"
    required: true
  token:
    description: "The token to use to access the GH API"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
